"use client"

/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline';
import { PerspectiveCamera } from '@react-three/drei';

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/RvM5JXTUfaonae5q/scene.splinecode');
  return (
    <>
      <group {...props} >
        <group name="Molang" position={[33.1, 20.41, 23.19]}>
          <mesh
            name="Body"
            geometry={nodes.Body.geometry}
            material={materials['Big Body']}
            receiveShadow
            position={[-19.44, -31.2, -23.27]}
            rotation={[0, 0, 0.09]}
            scale={1}
          />
          <mesh
            name="nose"
            geometry={nodes.nose.geometry}
            material={materials.Eyes}
            receiveShadow
            position={[-26.82, 86.76, 145.65]}
          />
          <mesh
            name="Sphere 3"
            geometry={nodes['Sphere 3'].geometry}
            material={materials.Eyes}
            castShadow
            receiveShadow
            position={[51.11, 82.72, 117.21]}
            rotation={[0, 0, 0.09]}
          />
          <mesh
            name="Sphere 2"
            geometry={nodes['Sphere 2'].geometry}
            material={materials.Eyes}
            receiveShadow
            position={[-112.82, 68.48, 117.21]}
            rotation={[0, 0, 0.09]}
          />
          <mesh
            name="Sphere"
            geometry={nodes.Sphere.geometry}
            material={materials['Big Body']}
            receiveShadow
            position={[-8.1, -165.45, -186.91]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            name="Cube 5"
            geometry={nodes['Cube 5'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[69.19, -78.2, 150.95]}
            rotation={[1.67, 0, -0.16]}
            scale={0.8}
          />
          <mesh
            name="Cube 7"
            geometry={nodes['Cube 7'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[71.21, -197.72, 36.96]}
            rotation={[3.02, -0.03, -0.45]}
            scale={0.8}
          />
          <mesh
            name="Cube 6"
            geometry={nodes['Cube 6'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[-101.62, -197.14, 41.89]}
            rotation={[3.02, -0.03, 0.13]}
            scale={0.8}
          />
          <mesh
            name="Cube 4"
            geometry={nodes['Cube 4'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[-62.17, -85.07, 168.16]}
            rotation={[1.67, 0, -0.4]}
            scale={0.8}
          />
          <mesh
            name="Cube 3"
            geometry={nodes['Cube 3'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[-17.23, 215.12, -8.87]}
            rotation={[0, 0, 0.38]}
            scale={0.93}
          />
          <mesh
            name="Cube 2"
            geometry={nodes['Cube 2'].geometry}
            material={materials['Big Body']}
            castShadow
            receiveShadow
            position={[-69.75, 208.7, -8.87]}
            rotation={[0, 0, -0.18]}
            scale={0.93}
          />
        </group>
        <directionalLight
          name="Directional Light"
          intensity={0.45}
          shadow-camera-near={-10000}
          shadow-camera-far={100000}
          shadow-camera-left={-500}
          shadow-camera-right={500}
          shadow-camera-top={500}
          shadow-camera-bottom={-500}
          position={[200, 300, 300]}
        />
        <PerspectiveCamera
          name="1"
          makeDefault={true}
          far={100000}
          near={70}
          fov={45}
          position={[0, 0, 1000]}
          rotation={[0, 0, 0]}
        />
        <hemisphereLight name="Default Ambient Light" intensity={0.75} color="#eaeaea" />
      </group>
    </>
  )
}
